name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # позволяет вручную запускать сборку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK (unsigned)
      run: ./gradlew assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Release APK (unsigned)
      uses: actions/upload-artifact@v3
      with:
        name: release-apk-unsigned
        path: app/build/outputs/apk/release/app-release-unsigned.apk
